version: '3'

services:
  libretv:
    image: bestzwei/libretv:latest
    container_name: libretv
    ports:
      - "8899:80"
    environment:
      - PASSWORD=111111  # 设置密码保护，留空则不启用密码
      # - PROXY_API=true  # 启用内部API代理，解决跨域问题
    restart: unless-stopped
    # volumes:
    #   - ./data:/usr/share/nginx/html/data
    # 如果希望使用构建模式而非拉取镜像
    # build:
    #   context: .
    #   dockerfile: Dockerfile